### ISSUE TITLE
00 being printed to the screen

### ISSUE THREAD

**Issue by TomClarkson** [riadchikhani/MessageParser#1]
I'm not sure why but 00 were being printed to the screen. I'm not sure why but it seemed to be generated in the if block below. When I removed it the 00 stopped being printed. Does this make any sense?

if ($this->config->get('message-parser::config.badwords.use_db')) {

**Comment by euantorano** [comment]
That's an odd one indeed. Do you have an example of where you were using
the system? Anyway, I will look into it.

**Comment by TomClarkson** [comment]
Here is the example. I have use_db set to false. 
![00 example](https://f.cloud.github.com/assets/2054503/1170568/3633b5da-20e2-11e3-9c7a-a404599ebe4e.png)

I'm not sure why the 00 appears to be being printed in the use_db if block as that evaluates to false. I have a multi-language site so we will compile bad words in different languages and merge them into the badwords array. I can share these language files with you if you would like. Many thanks

**Comment by euantorano** [comment]
Odd. I will spin up a test instance tonight and have a look after work. Thanks for the report.

**Comment by TomClarkson** [comment]
Hi there did you get the same bug when you looked at it?

**Comment by euantorano** [comment]
Hey, sorry for the late response. I have not been able to reproduce this on my setup at all. Do you have any details on your actual installation (PHP version, Laravel version)? That way I can set up a Vagrant instance to test with.
